### ISSUE TITLE
Issue when about to level up

### ISSUE THREAD

**Issue by higps** [Mikusch/MannVsMann#14] opened 2021-12-27 12:07 UTC
I was just test shooting some bots with the brass beast with penetration upgrade, right before getting the exp update.

Then nobody took any damage and I get this error
L 12/27/2021 - 12:04:20: [SM] Blaming: mannvsmann.smx
L 12/27/2021 - 12:04:20: [SM] Call stack trace:
L 12/27/2021 - 12:04:20: [SM]   [1] Line 130, d:\tf2server\tf2\tf\addons\sourcemod\scripting\mannvsmann/helpers.sp::SetMannVsMachineMode
L 12/27/2021 - 12:04:20: [SM]   [2] Line 66, d:\tf2server\tf2\tf\addons\sourcemod\scripting\mannvsmann/sdkhooks.sp::Client_OnTakeDamageAlive
L 12/27/2021 - 12:04:20: [SM] Exception reported: Array index out-of-bounds (index 8, limit 8)

L 12/27/2021 - 12:05:46: [SM] Exception reported: Array index out-of-bounds (index 8, limit 8)
L 12/27/2021 - 12:05:46: [SM] Blaming: mannvsmann.smx
L 12/27/2021 - 12:05:46: [SM] Call stack trace:
L 12/27/2021 - 12:05:46: [SM]   [1] Line 137, d:\tf2server\tf2\tf\addons\sourcemod\scripting\mannvsmann/helpers.sp::ResetMannVsMachineMode
L 12/27/2021 - 12:05:46: [SM]   [2] Line 297, d:\tf2server\tf2\tf\addons\sourcemod\scripting\mannvsmann/dhooks.sp::DHookCallback_CanRecieveMedigunChargeEffect_Post
L 12/27/2021 - 12:05:46: [SM]   [4] SDKCall
L 12/27/2021 - 12:05:46: [SM]   [5] Line 285, d:\tf2server\tf2\tf\addons\sourcemod\scripting\mannvsmann/sdkcalls.sp::SDKCall_CanRecieveMedigunChargeEffect
L 12/27/2021 - 12:05:46: [SM]   [6] Line 489, d:\tf2server\tf2\tf\addons\sourcemod\scripting\mannvsmann.sp::OnClientCommandKeyValues

**Comment by Mikusch** [comment] 2021-12-27 12:15
What do you mean with leveling up? Are you using the `bounty` branch?

**Comment by higps** [comment] 2022-01-15 13:48
I was using the latest release branch

**Comment by Mikusch** [comment] 2022-01-15 14:03
Could you elaborate what you mean with "leveling up"?

**Comment by higps** [comment] 2022-01-29 18:24
When a strange is about the change level, when turning from one strange to another this happens

**Comment by Mikusch** [comment] 2022-03-18 21:12
Closing because I couldn't reproduce this. It's likely you have something else going on here.

**Closed by Mikusch** 2022-03-18 21:12 UTC
